input: "/mnt/AchTeraD/data/BICRO204/fastq/"
samplename: "NZ19_S1"
output: "/mnt/AchTeraD/data/BICRO204/NZ19/"
ref: "/mnt/AchTeraD/Documents/references/hg19/hg19.fa"
refname: 'hg19'
bc: "/mnt/AchTeraD/data/BICRO204/barcodes/96barcodes.csv"
threads: 32
demux: /home/luukharbers/BBMap_38.76/bbmap/demuxbyname.sh