# Sample related
indir: "/mnt/AchTeraD/data/BICRO229/fastq/NEB/"
outdir: "/mnt/AchTeraD/data/BICRO229/NEBNext/"
paired: False

# References
ref: "/mnt/AchTeraD/Documents/references/hg19/hg19.fa"
refname: 'hg19'

# Tools
alfred: "/home/luukharbers/alfred/bin/alfred"

# Threads
threads: 32
