# Sample related
input: "/mnt/AchTeraD/data/BICRO253/fastq/"
samplename: "NZ184_S1"
output: "/mnt/AchTeraD/data/BICRO253/NZ184/"
paired: False
lanesplit: True

# Semi-static
bc: "/mnt/AchTeraD/data/384_NlaIII-barcodes.txt"
cutsites: "/mnt/AchTeraD/Documents/Projects/scCUTseq/cutsite-distribution/mm10_cutsites-fixed.tsv"
mismatches: 2
barcode_length: 11
read_length: 56 # After removing barcodes etc 56 // 130

# References
ref: "/mnt/AchTeraD/Documents/references/mm10/mm10.fa"
refname: 'mm10'

# Tools
demux: "python /mnt/AchTeraD/Documents/Projects/scCUTseq/Scripts/preprocessing-pipeline/demultiplex/demultiplex_withcython.py"
combineLogs: "/mnt/AchTeraD/Documents/Projects/scCUTseq/Scripts/preprocessing-pipeline/combine_logfiles.R"
getReads: "/mnt/AchTeraD/Documents/Projects/scCUTseq/Scripts/preprocessing-pipeline/Extract_readnames_nearCutsites.R"
alfred: "/home/luukharbers/alfred/bin/alfred"

# Threads
threads: 32
