run_info:
  run: "BICRO284"
  library: "MS160"
  base_path: "/mnt/AchTeraD/data/"
  threads: 32

paths:
  binbed_file: "files/hg19/150/variable_{binsize}_150_bwa.bed"
  bin_file: "files/hg19/150/variable_{binsize}_150_bwa"
  gc_file: "files/hg19/150/GC_variable_{binsize}_150_bwa"
  bnd_file: "files/hg19/150/bounds_variable_{binsize}_150_bwa"
  blacklist: "files/hg19/150/hg19-blacklist.v2_adjusted.bed"
  normal: "files/hg19/150/normalize.tsv"

#paths:
#  binbed_file: "files/mm10/48/variable_{binsize}_48_bwa.bed"
#  bin_file: "files/mm10/48/variable_{binsize}_48_bwa"
#  gc_file: "files/mm10/48/GC_variable_{binsize}_48_bwa"
#  bnd_file: "files/mm10/48/bounds_variable_{binsize}_48_bwa"
#  blacklist: "files/mm10/48/hg19-blacklist.v2_adjusted.bed"
#  normal: "files/mm10/48/normalize.tsv"
#  normal: "files/empty-normal.tsv"


dnacopy:
  # Which binsizes to run
  binsizes: [500000]
  # Minimum MAPQ score to use for binned reads
  min_mapq: 30
  # Minimum reads / cell
  min_count: 50000
  # Parameters for DNA copy segmentation
  cbs_minwidth: 3
  cbs_alpha: 0.001
  cbs_undosplits: "none"
  cbs_sdprune: 3
  cbs_remove_outlier_bins: 1
