run_info:
  run: "ngi/P18158_combined"
  library: "NZ120"

  base_path: "/mnt/AchTeraD/data/"
  threads: 32

paths:
  binbed_file: "files/variable_{binsize}_48_bwa.bed"
  bin_file: "files/variable_{binsize}_48_bwa"
  gc_file: "files/GC_variable_{binsize}_48_bwa"
  bnd_file: "files/bounds_variable_{binsize}_48_bwa"
  blacklist: "files/hg19-blacklist.v2_adjusted.bed"
  normal: "files/BICRO243_MS67-normal-{binsize}.tsv"



dnacopy:
  # Which binsizes to run
  binsizes: [500000, 250000, 175000, 100000, 50000]
  # Minimum MAPQ score to use for binned reads
  min_mapq: 30
  # Minimum reads / cell
  min_count: 50000
  # Parameters for DNA copy segmentation
  cbs_minwidth: 3
  cbs_alpha: 0.001
  cbs_undosplits: "none"
  cbs_sdprune: 3
  cbs_remove_outlier_bins: 1
